#!/usr/bin/env bash
#commands to install nginx on the server

#update packages
sudo apt-get update

#install nginx
sudo apt-get install -y nginx

#allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

#creating index-html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

#starting
sudo service nginx start

